version: "3.8"
services:
  app1:
    image: 127.0.0.1:5000/phrase
    build: .
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - APP_PORT=5001
      - REDIS_HOST=redis

  app2:
    image: 127.0.0.1:5000/phrase
    build: .
    ports:
      - "5002:5002"
    restart: unless-stopped
    environment:
      - APP_PORT=5002
      - REDIS_HOST=redis

  redis:
    image: redis:alpine